#!/usr/bin/env python3
"""Generate enemy state tables + sprite plumbing from docs/data/state_tables.json.

This IS the ledger's state-table diff made literal: the generated ZScript
arrays are the source's statetype rows, one to one. The WolfEnemySim
interpreter (enemies.zs) executes them at Wolf-tic fidelity.

Currently generates: guard. Per-enemy extension = add a SPRITES mapping and
a state list; the interpreter is shared.

Outputs (generated, never hand-edit):
  src/zscript/enemies.gen.zs      state tables + state-index constants
  src/mapinfo_enemies.txt         DoomEdNums include
  src/sprites/*.png               placeholders (make_assets overrides)
  docs/data/sprite_copies.json    chunk->lump copy list for make_assets
"""
import json
import re
import struct
import zlib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "reference" / "wolfsrc" / "WOLFSRC"

THINKS = {"None": 0, "T_Stand": 1, "T_Path": 2, "T_Chase": 3, "T_Shoot": 4,
          "T_Bite": 5, "A_DeathScream": 10, "A_StartDeathCam": 11,
          "T_Ghosts": 12, "T_DogChase": 13, "A_HitlerMorph": 14}

# WL6 sprite-enum index (SPR_STAT_0 = 2 base; conditional-aware)
def sprite_enum():
    text = (SRC / "WL_DEF.H").read_text(errors="replace")
    start = text.find("SPR_DEMO")
    lines = text[start:text.find("}", start)].splitlines()
    names, stack = [], []
    for ln in lines:
        s = ln.strip()
        if s.startswith("#ifdef"):
            stack.append(False if s.split()[1] == "SPEAR" else False)
            continue
        if s.startswith("#ifndef"):
            stack.append(s.split()[1] == "SPEAR")
            continue
        if s.startswith("#else"):
            if stack:
                stack[-1] = not stack[-1]
            continue
        if s.startswith("#endif"):
            if stack:
                stack.pop()
            continue
        if all(stack):
            names += re.findall(r"\b(SPR_[A-Z0-9_]+)\b", ln)
    return {n: i for i, n in enumerate(names)}


# sprite name mapping: SPR_* -> (doom sprite, frame char, rotated)
GUARD_SPRITES = {
    "SPR_GRD_S_1":   ("GRDS", "A", True),
    "SPR_GRD_W1_1":  ("GRDW", "A", True),
    "SPR_GRD_W2_1":  ("GRDW", "B", True),
    "SPR_GRD_W3_1":  ("GRDW", "C", True),
    "SPR_GRD_W4_1":  ("GRDW", "D", True),
    "SPR_GRD_PAIN_1": ("GRDP", "A", "pain"),
    "SPR_GRD_PAIN_2": ("GRDP", "B", "pain"),
    "SPR_GRD_DIE_1": ("GRDD", "A", False),
    "SPR_GRD_DIE_2": ("GRDD", "B", False),
    "SPR_GRD_DIE_3": ("GRDD", "C", False),
    "SPR_GRD_DEAD":  ("SDED", "A", False),
    "SPR_GRD_SHOOT1": ("GRDA", "A", False),
    "SPR_GRD_SHOOT2": ("GRDA", "B", False),
    "SPR_GRD_SHOOT3": ("GRDA", "C", False),
}

GUARD_STATES = ["s_grdstand",
                "s_grdpath1", "s_grdpath1s", "s_grdpath2", "s_grdpath3",
                "s_grdpath3s", "s_grdpath4",
                "s_grdpain", "s_grdpain1",
                "s_grdshoot1", "s_grdshoot2", "s_grdshoot3",
                "s_grdchase1", "s_grdchase1s", "s_grdchase2", "s_grdchase3",
                "s_grdchase3s", "s_grdchase4",
                "s_grddie1", "s_grddie2", "s_grddie3", "s_grddie4"]


def placeholder_png():
    def chunk(tag, payload):
        return (struct.pack(">I", len(payload)) + tag + payload
                + struct.pack(">I", zlib.crc32(tag + payload)))
    ihdr = struct.pack(">IIBBBBB", 1, 1, 8, 6, 0, 0, 0)
    idat = zlib.compress(b"\x00\x00\x00\x00\x00")
    return (b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", ihdr)
            + chunk(b"grAb", struct.pack(">ii", 0, 0))
            + chunk(b"IDAT", idat) + chunk(b"IEND", b""))


def main():
    states = {s["name"]: s for s in json.loads(
        (ROOT / "docs" / "data" / "state_tables.json").read_text())["states"]}
    enum = sprite_enum()
    idx_of = {n: i for i, n in enumerate(GUARD_STATES)}

    rot_l, spr_l, frm_l, tic_l, thk_l, act_l, nxt_l = [], [], [], [], [], [], []
    consts = []
    for name in GUARD_STATES:
        st = states[name]
        sprname, frame, rotated = GUARD_SPRITES[st["sprite"]]
        rot_l.append({"true": 1, "false": 0, "1": 1, "2": 2}[st["rotate"]])
        spr_l.append(sprname)
        frm_l.append(ord(frame) - 65)
        tic_l.append(int(st["tics"]))
        thk_l.append(THINKS[st["think"] or "None"])
        act_l.append(THINKS[st["action"] or "None"])
        nxt = st["next"]
        nxt_l.append(idx_of.get(nxt, -1) if nxt else -1)
        consts.append(f"    const {name[2:].upper()} = {idx_of[name]};")

    def arr(name, vals, quote=False):
        items = ", ".join(f'"{v}"' if quote else str(v) for v in vals)
        t = "String" if quote else "int"
        return f"    static const {t} {name}[] = {{ {items} }};"

    zs = ["// GENERATED by tools/gen_enemies.py from docs/data/state_tables.json",
          "// Rows are WL_ACT2.C statetype entries, one to one. Do not edit.",
          "",
          "class WolfGuardTable",
          "{"] + consts + [
          arr("ROT", rot_l), arr("SPR", spr_l, True), arr("FRM", frm_l),
          arr("TICS", tic_l), arr("THINK", thk_l), arr("ACT", act_l),
          arr("NEXT", nxt_l),
          "}", ""]
    (ROOT / "src" / "zscript" / "enemies.gen.zs").write_text("\n".join(zs) + "\n")

    (ROOT / "src" / "mapinfo_enemies.txt").write_text(
        "// GENERATED by tools/gen_enemies.py — included from MAPINFO\n"
        "DoomEdNums\n{\n"
        '    21001 = "WolfGuardStand"\n'
        '    21002 = "WolfGuardPatrol"\n'
        "}\n")

    # sprite copy list for make_assets + placeholders
    copies = []
    base = enum["SPR_GRD_S_1"]          # 50 in WL6
    for r in range(8):
        copies.append([base + r, f"GRDSA{r + 1}"])
    for f, spr in enumerate(["SPR_GRD_W1_1", "SPR_GRD_W2_1",
                             "SPR_GRD_W3_1", "SPR_GRD_W4_1"]):
        b = enum[spr]
        for r in range(8):
            copies.append([b + r, f"GRDW{chr(65 + f)}{r + 1}"])
    # pain: rotate==2 art — CalcRotate returns +0 (angle<180) or +4:
    # engine rots 1-4 approximate the +0 half, 5-8 the +4 half (22.5deg
    # wedge approximation, decision-logged). GRDP B rots 5-8 land on
    # SHOOT1 — the original's art-layout quirk, preserved.
    p1, p2 = enum["SPR_GRD_PAIN_1"], enum["SPR_GRD_PAIN_2"]
    for r in range(1, 5):
        copies.append([p1, f"GRDPA{r}"])
        copies.append([p2, f"GRDPB{r}"])
    for r in range(5, 9):
        copies.append([p1 + 4, f"GRDPA{r}"])
        copies.append([p2 + 4, f"GRDPB{r}"])
    for f, spr in enumerate(["SPR_GRD_DIE_1", "SPR_GRD_DIE_2", "SPR_GRD_DIE_3"]):
        copies.append([enum[spr], f"GRDD{chr(65 + f)}0"])
    for f, spr in enumerate(["SPR_GRD_SHOOT1", "SPR_GRD_SHOOT2",
                             "SPR_GRD_SHOOT3"]):
        copies.append([enum[spr], f"GRDA{chr(65 + f)}0"])
    (ROOT / "docs" / "data" / "sprite_copies.json").write_text(
        json.dumps({"note": "chunk -> sprite lump (gen_enemies.py)",
                    "copies": copies}, indent=1))

    ph = placeholder_png()
    for _, lump in copies:
        (ROOT / "src" / "sprites" / f"{lump}.png").write_bytes(ph)

    print(f"generated guard: {len(GUARD_STATES)} states, "
          f"{len(copies)} sprite lumps")


if __name__ == "__main__":
    main()
