#!/usr/bin/env python3
"""Generate static-object actors from docs/data/statinfo.json (WL6 build).

Emits (all marked generated — never hand-edit, rerun this tool):
  src/zscript/statics.gen.zs   one actor per WL6 statinfo row
  src/mapinfo_statics.txt      DoomEdNums block (included from MAPINFO)
  src/sprites/S0nnA0.png       1x1 transparent placeholders so the IPK3
                               boots without user data (real sprites from
                               make_assets override them at build time)

Row semantics (charter statinfo/DATA-004):
  block    -> +SOLID radius 32 (actorat=1 blocks the whole tile; with
              PLAYERSIZE 22 the square 32-radius box reproduces TryMove's
              keep-out exactly), shots pass (never FL_SHOOTABLE), but
              projectiles hit (ProjectileTryMove stops on actorat<256)
  dressing -> non-blocking decoration
  bo_*     -> pickup: rendered non-blocking for now; pickup logic lands
              with the Phase 2 items pass (GetBonus rules PICK-001..011)

Sprite chunk = 2 + row.sprite (SPR_STAT_0 = 2, WL_DEF.H enum, WL6 build);
object code = 23 + position in the per-build array (MAP-002), so DoomEd =
21100 + position.
"""
import json
import struct
import zlib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "docs" / "data" / "statinfo.json"

WL6_CONDS = (None, "ifndef SPEAR", "!ifdef SPEAR")


def wl6_rows():
    rows = json.loads(DATA.read_text())["rows"]
    return [r for r in rows if r["cond"] in WL6_CONDS]


def placeholder_png():
    """1x1 transparent PNG with grAb(0,0)."""
    def chunk(tag, payload):
        return (struct.pack(">I", len(payload)) + tag + payload
                + struct.pack(">I", zlib.crc32(tag + payload)))
    ihdr = struct.pack(">IIBBBBB", 1, 1, 8, 6, 0, 0, 0)
    idat = zlib.compress(b"\x00\x00\x00\x00\x00")
    return (b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", ihdr)
            + chunk(b"grAb", struct.pack(">ii", 0, 0))
            + chunk(b"IDAT", idat) + chunk(b"IEND", b""))


def main():
    rows = wl6_rows()
    zs = ["// GENERATED by tools/gen_statics.py from docs/data/statinfo.json",
          "// (WL6 build). Do not edit; rerun the tool.", ""]
    eds = ["// GENERATED by tools/gen_statics.py — included from MAPINFO",
           "DoomEdNums", "{"]
    spr_dir = ROOT / "src" / "sprites"
    spr_dir.mkdir(exist_ok=True)
    ph = placeholder_png()

    BO_KINDS = {"bo_firstaid": "BO_FIRSTAID", "bo_food": "BO_FOOD",
                "bo_alpo": "BO_ALPO", "bo_gibs": "BO_GIBS",
                "bo_clip": "BO_CLIP", "bo_clip2": "BO_CLIP2",
                "bo_25clip": "BO_25CLIP", "bo_machinegun": "BO_MACHINEGUN",
                "bo_chaingun": "BO_CHAINGUN", "bo_cross": "BO_CROSS",
                "bo_chalice": "BO_CHALICE", "bo_bible": "BO_BIBLE",
                "bo_crown": "BO_CROWN", "bo_fullheal": "BO_FULLHEAL",
                "bo_key1": "BO_KEY1", "bo_key2": "BO_KEY2"}
    for pos, r in enumerate(rows):
        cls = f"WolfStatic{pos:02d}"
        spr = f"S{pos:03d}"
        comment = r["comment"] or "?"
        zs.append(f"// statinfo[{pos}] sprite SPR_STAT_{r['sprite']}: {comment}")
        if r["class"] in BO_KINDS:
            # pickup: GetBonus semantics live in WolfPickup (items.zs)
            zs.append(f"class {cls} : WolfPickup")
            zs.append("{")
            zs.append("    States\n    {\n    Spawn:")
            zs.append(f"        {spr} A -1;\n        Stop;\n    }}")
            zs.append("    override int BonusKind() "
                      f"{{ return WolfPickup.{BO_KINDS[r['class']]}; }}")
            zs.append("}")
        else:
            if r["class"] == "block":
                body = ("        +SOLID\n        Radius 32;\n        Height 64;"
                        "\n        +NOGRAVITY")
            else:
                body = "        +NOBLOCKMAP\n        +NOGRAVITY"
            zs.append(f"class {cls} : Actor")
            zs.append("{")
            zs.append("    Default\n    {")
            zs.append(body)
            zs.append("    }")
            zs.append("    States\n    {\n    Spawn:")
            zs.append(f"        {spr} A -1;\n        Stop;\n    }}")
            zs.append("}")
        zs.append("")
        eds.append(f"    {21100 + pos} = \"{cls}\"")
        (spr_dir / f"{spr}A0.png").write_bytes(ph)

    # dead guard decoration (SpawnDeadGuard -> inertobj, non-blocking)
    zs += ["// dead guard (map code 124, MAP-004): SPR_GRD_DEAD, inert",
           "class WolfDeadGuard : Actor",
           "{",
           "    Default\n    {",
           "        +NOBLOCKMAP\n        +NOGRAVITY",
           "    }",
           "    States\n    {\n    Spawn:",
           "        SDED A -1;\n        Stop;\n    }",
           "}", ""]
    eds.append('    21212 = "WolfDeadGuard"')
    (spr_dir / "SDEDA0.png").write_bytes(ph)

    eds.append("}")
    (ROOT / "src" / "zscript" / "statics.gen.zs").write_text("\n".join(zs) + "\n")
    (ROOT / "src" / "mapinfo_statics.txt").write_text("\n".join(eds) + "\n")
    print(f"generated {len(rows)} statics + dead guard "
          f"({sum(1 for r in rows if r['class']=='block')} blocking)")


if __name__ == "__main__":
    main()
