#!/usr/bin/env python3
"""Emit the Wolf3D palette as a ZScript lookup.

Screens that reproduce the original's drawing talk in palette indices
(fontcolor 0x7e, BACKCOLOR 0x11, VIEWCOLOR 127), so the renderer needs
the same 256 RGB values the game used rather than eyeballed colours.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from wolf_common import ROOT, load_palette

pal = load_palette()
lines = ["// GENERATED by tools/gen_palette.py — GAMEPAL, 256 entries",
         "class WolfPal",
         "{",
         "    static clearscope Color Get(int i)",
         "    {",
         "        static const int RGB[] = {"]
rows = []
for i in range(0, 256, 8):
    rows.append(", ".join("0x%02x%02x%02x" % tuple(pal[j])
                          for j in range(i, i + 8)))
for i, row in enumerate(rows):
    lines.append(f"            {row}" + ("," if i < len(rows) - 1 else ""))
lines.append("        };")
lines.append("        i = i & 255;")
lines.append("        return Color((RGB[i] >> 16) & 255, (RGB[i] >> 8) & 255,")
lines.append("                     RGB[i] & 255);")
lines.append("    }")
lines.append("}")
(ROOT / "src" / "zscript" / "palette.gen.zs").write_text(
    "\n".join(lines) + "\n")
print("generated palette.gen.zs (256 colors)")
