#!/usr/bin/env python3
"""Generate src/mapinfo_maps.txt: all 60 WL6 map defs with names, levelnums,
and per-level music from the songs[] table (WL_PLAY.C:107-199).

Music lump names are the track names minus _MUS (all <= 8 chars), matching
make_assets' music copies.
"""
from pathlib import Path
import json

ROOT = Path(__file__).resolve().parent.parent

# songs[] per episode slot (WL_PLAY.C): 10 slots x 6 episodes
# ElevatorBackTo[] (WL_GAME.C:39): 0-based mapon the secret floor returns to
ELEVATOR_BACK_TO = [1, 1, 7, 3, 5, 3]

# par times (TALLY-001): the source stores minutes; MAPINFO wants seconds
PAR = json.loads((ROOT / "docs" / "data" / "par_times.json").read_text())["wl6"]

EP_SONGS = [
    ["GETTHEM", "SEARCHN", "POW", "SUSPENSE", "GETTHEM", "SEARCHN", "POW",
     "SUSPENSE", "WARMARCH", "CORNER"],
    ["NAZI_OMI", "PREGNANT", "GOINGAFT", "HEADACHE", "NAZI_OMI", "PREGNANT",
     "HEADACHE", "GOINGAFT", "WARMARCH", "DUNGEON"],
    ["INTROCW3", "NAZI_RAP", "TWELFTH", "ZEROHOUR", "INTROCW3", "NAZI_RAP",
     "TWELFTH", "ZEROHOUR", "ULTIMATE", "PACMAN"],
    ["GETTHEM", "SEARCHN", "POW", "SUSPENSE", "GETTHEM", "SEARCHN", "POW",
     "SUSPENSE", "WARMARCH", "CORNER"],
    ["NAZI_OMI", "PREGNANT", "GOINGAFT", "HEADACHE", "NAZI_OMI", "PREGNANT",
     "HEADACHE", "GOINGAFT", "WARMARCH", "DUNGEON"],
    ["INTROCW3", "NAZI_RAP", "TWELFTH", "ZEROHOUR", "INTROCW3", "NAZI_RAP",
     "TWELFTH", "ZEROHOUR", "ULTIMATE", "FUNKYOU"],
]


def main():
    lines = ["// GENERATED by tools/gen_mapinfo.py — included from MAPINFO",
             "// Map names from GAMEMAPS; music per WL_PLAY.C songs[]", ""]
    levels = ROOT / "build" / "levels" / "wl6"
    for n in range(60):
        ep, slot = n // 10, n % 10
        name = f"Wolf{ep + 1} Map{slot + 1}"
        f = levels / f"MAP{n:02d}.json"
        if f.exists():
            name = json.loads(f.read_text())["name"]
        mapname = f"MAP{n + 1:02d}"
        # progression (WL_GAME.C:1386-1400): floors 1-8 advance in order;
        # the secret floor (slot 9) returns to ElevatorBackTo[episode];
        # the boss floor (slot 8) ends the episode via the victory tile.
        if slot == 9:
            nxt = ep * 10 + ELEVATOR_BACK_TO[ep] + 1
        elif slot == 8:
            nxt = -1                        # boss floor: the episode ends
        else:
            nxt = n + 2
        secret = ep * 10 + 10               # slot 9 of this episode
        lines.append(f'map {mapname} "{name}"')
        lines.append("{")
        lines.append(f"    levelnum = {n + 1}")
        lines.append(f'    music = "{EP_SONGS[ep][slot]}"')
        if nxt < 0:
            # The boss floor ends the episode. It cannot use MAPINFO's
            # "EndTitle" or an endgame block: EndTitle skips the
            # intermission (which is where Victory() draws the episode
            # averages) and the endgame block is rejected by the parser.
            # So the floor keeps a placeholder next and WolfIntermission
            # takes over in victoryMode; the real chain out of it
            # (EndText -> high scores -> title) lands there.
            lines.append(f'    next = "MAP{ep * 10 + 1:02d}"')
        else:
            lines.append(f'    next = "MAP{nxt:02d}"')
        lines.append(f'    secretnext = "MAP{secret:02d}"')
        lines.append(f"    par = {int(round(PAR[n]['minutes'] * 60))}")
        lines.append("}")
        lines.append("")
    (ROOT / "src" / "mapinfo_maps.txt").write_text("\n".join(lines) + "\n")
    print("generated mapinfo_maps.txt (60 maps)")


if __name__ == "__main__":
    main()
