#!/usr/bin/env python3
"""Generate src/zscript/rng.gen.zs from docs/data/rndtable.json (RNG-001).

The 256-entry US_RndT table, verbatim. Index state lives in WolfLevel.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

def main():
    vals = json.loads((ROOT / "docs" / "data" / "rndtable.json").read_text())["values"]
    assert len(vals) == 256
    rows = [", ".join(str(v) for v in vals[i:i + 16]) for i in range(0, 256, 16)]
    body = ",\n        ".join(rows)
    (ROOT / "src" / "zscript" / "rng.gen.zs").write_text(
        "// GENERATED by tools/gen_rng.py from docs/data/rndtable.json\n"
        "// (ID_US_A.ASM rndtable, charter RNG-001). Do not edit.\n"
        "class WolfRndTable\n{\n"
        "    static const int T[] = {\n        " + body + "\n    };\n}\n")
    print("generated rng.gen.zs (256 entries)")

if __name__ == "__main__":
    main()
