#!/usr/bin/env python3
"""Generate static-object actors from docs/data/statinfo.json.

BOTH game sets are generated into the shared zscript tree: the WL6 rows
as WolfStatic00.. (sprites S000.., DoomEd 21100+) and the Spear rows as
SodStatic00.. (sprites D000.., DoomEd 21300+). Each ipk3 carries only
its own sprite lumps; the other set's classes never spawn there, and an
unspawned actor's missing sprite name is harmless (a -1 sprite only
bites when such an actor actually enters view).

Emits (all marked generated - never hand-edit, rerun this tool):
  src/zscript/statics.gen.zs   one actor per statinfo row, both sets
  src/mapinfo_statics.txt      DoomEdNums block (included from MAPINFO)
  src/sprites/S0nnA0.png       1x1 transparent placeholders so the IPK3
  src/sprites/D0nnA0.png       boots without user data (real sprites from
                               make_assets override them at build time)

Row semantics (charter statinfo/DATA-004):
  block    -> +SOLID radius 32 (actorat=1 blocks the whole tile; with
              PLAYERSIZE 22 the square 32-radius box reproduces TryMove's
              keep-out exactly), shots pass (never FL_SHOOTABLE), but
              projectiles hit (ProjectileTryMove stops on actorat<256)
  dressing -> non-blocking decoration
  bo_*     -> pickup: GetBonus rules PICK-001..011 live in WolfPickup

Sprite chunk = 2 + row.sprite (SPR_STAT_0 = 2 in each build's WL_DEF.H
enum); object code = 23 + position in the per-build array (MAP-002).
"""
import json
import struct
import zlib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "docs" / "data" / "statinfo.json"

WL6_CONDS = (None, "ifndef SPEAR", "!ifdef SPEAR")
SOD_CONDS = (None, "ifdef SPEAR", "!ifndef SPEAR")

# per-set: name, class prefix, sprite prefix, DoomEd base, statinfo conds
SETS = (
    ("wl6", "WolfStatic", "S", 21100, WL6_CONDS),
    ("sod", "SodStatic", "D", 21300, SOD_CONDS),
)

BO_KINDS = {"bo_firstaid": "BO_FIRSTAID", "bo_food": "BO_FOOD",
            "bo_alpo": "BO_ALPO", "bo_gibs": "BO_GIBS",
            "bo_clip": "BO_CLIP", "bo_clip2": "BO_CLIP2",
            "bo_25clip": "BO_25CLIP", "bo_machinegun": "BO_MACHINEGUN",
            "bo_chaingun": "BO_CHAINGUN", "bo_cross": "BO_CROSS",
            "bo_chalice": "BO_CHALICE", "bo_bible": "BO_BIBLE",
            "bo_crown": "BO_CROWN", "bo_fullheal": "BO_FULLHEAL",
            "bo_key1": "BO_KEY1", "bo_key2": "BO_KEY2"}


def rows_for(conds):
    rows = json.loads(DATA.read_text())["rows"]
    return [r for r in rows if r["cond"] in conds]


def placeholder_png():
    """1x1 transparent PNG with grAb(0,0)."""
    def chunk(tag, payload):
        return (struct.pack(">I", len(payload)) + tag + payload
                + struct.pack(">I", zlib.crc32(tag + payload)))
    ihdr = struct.pack(">IIBBBBB", 1, 1, 8, 6, 0, 0, 0)
    idat = zlib.compress(b"\x00\x00\x00\x00\x00")
    return (b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", ihdr)
            + chunk(b"grAb", struct.pack(">ii", 0, 0))
            + chunk(b"IDAT", idat) + chunk(b"IEND", b""))


def emit_actor(zs, cls, spr, row):
    """one statinfo row -> a ZScript actor definition"""
    if row["class"] in BO_KINDS:
        zs.append("class %s : WolfPickup" % cls)
        zs.append("{")
        zs.append("    States")
        zs.append("    {")
        zs.append("    Spawn:")
        zs.append("        %s A -1;" % spr)
        zs.append("        Stop;")
        zs.append("    }")
        zs.append("    override int BonusKind() { return WolfPickup.%s; }"
                  % BO_KINDS[row["class"]])
        zs.append("}")
        return
    zs.append("class %s : Actor" % cls)
    zs.append("{")
    zs.append("    Default")
    zs.append("    {")
    if row["class"] == "block":
        zs.append("        +SOLID")
        zs.append("        Radius 32;")
        zs.append("        Height 64;")
        zs.append("        +NOGRAVITY")
    else:
        zs.append("        +NOBLOCKMAP")
        zs.append("        +NOGRAVITY")
    zs.append("    }")
    zs.append("    States")
    zs.append("    {")
    zs.append("    Spawn:")
    zs.append("        %s A -1;" % spr)
    zs.append("        Stop;")
    zs.append("    }")
    zs.append("}")


def main():
    zs = ["// GENERATED by tools/gen_statics.py from docs/data/statinfo.json",
          "// (both game sets). Do not edit; rerun the tool.", ""]
    eds = ["// GENERATED by tools/gen_statics.py - included from MAPINFO",
           "DoomEdNums", "{"]
    spr_dir = ROOT / "src" / "sprites"
    spr_dir.mkdir(exist_ok=True)
    ph = placeholder_png()
    counts = []

    for setname, clsbase, sprbase, edbase, conds in SETS:
        rows = rows_for(conds)
        counts.append("%s %d" % (setname, len(rows)))
        zs.append("// ---------------- %s statics ----------------" % setname)
        zs.append("")
        eds.append("    // %s" % setname)
        for pos, row in enumerate(rows):
            cls = "%s%02d" % (clsbase, pos)
            spr = "%s%03d" % (sprbase, pos)
            zs.append("// statinfo[%d] sprite SPR_STAT_%d: %s"
                      % (pos, row["sprite"], row["comment"] or "?"))
            emit_actor(zs, cls, spr, row)
            zs.append("")
            eds.append('    %d = "%s"' % (edbase + pos, cls))
            (spr_dir / ("%sA0.png" % spr)).write_bytes(ph)

    # dead guard decoration (SpawnDeadGuard -> inertobj, non-blocking).
    # Shared: both builds put SPR_GRD_DEAD under the same lump name.
    zs += ["// dead guard (map code 124, MAP-004): SPR_GRD_DEAD, inert",
           "class WolfDeadGuard : Actor",
           "{",
           "    Default",
           "    {",
           "        +NOBLOCKMAP",
           "        +NOGRAVITY",
           "    }",
           "    States",
           "    {",
           "    Spawn:",
           "        SDED A -1;",
           "        Stop;",
           "    }",
           "}", ""]
    eds.append('    21212 = "WolfDeadGuard"')
    (spr_dir / "SDEDA0.png").write_bytes(ph)

    eds.append("}")
    (ROOT / "src" / "zscript" / "statics.gen.zs").write_text(
        "\n".join(zs) + "\n")
    (ROOT / "src" / "mapinfo_statics.txt").write_text("\n".join(eds) + "\n")
    print("generated statics: %s + dead guard" % ", ".join(counts))


if __name__ == "__main__":
    main()
