#!/usr/bin/env python3
"""Generate src/mapinfo_maps.txt: all 60 WL6 map defs with names, levelnums,
and per-level music from the songs[] table (WL_PLAY.C:107-199).

Music lump names are the track names minus _MUS (all <= 8 chars), matching
make_assets' music copies.
"""
from pathlib import Path
import json

ROOT = Path(__file__).resolve().parent.parent

# songs[] per episode slot (WL_PLAY.C): 10 slots x 6 episodes
EP_SONGS = [
    ["GETTHEM", "SEARCHN", "POW", "SUSPENSE", "GETTHEM", "SEARCHN", "POW",
     "SUSPENSE", "WARMARCH", "CORNER"],
    ["NAZI_OMI", "PREGNANT", "GOINGAFT", "HEADACHE", "NAZI_OMI", "PREGNANT",
     "HEADACHE", "GOINGAFT", "WARMARCH", "DUNGEON"],
    ["INTROCW3", "NAZI_RAP", "TWELFTH", "ZEROHOUR", "INTROCW3", "NAZI_RAP",
     "TWELFTH", "ZEROHOUR", "ULTIMATE", "PACMAN"],
    ["GETTHEM", "SEARCHN", "POW", "SUSPENSE", "GETTHEM", "SEARCHN", "POW",
     "SUSPENSE", "WARMARCH", "CORNER"],
    ["NAZI_OMI", "PREGNANT", "GOINGAFT", "HEADACHE", "NAZI_OMI", "PREGNANT",
     "HEADACHE", "GOINGAFT", "WARMARCH", "DUNGEON"],
    ["INTROCW3", "NAZI_RAP", "TWELFTH", "ZEROHOUR", "INTROCW3", "NAZI_RAP",
     "TWELFTH", "ZEROHOUR", "ULTIMATE", "FUNKYOU"],
]


def main():
    lines = ["// GENERATED by tools/gen_mapinfo.py — included from MAPINFO",
             "// Map names from GAMEMAPS; music per WL_PLAY.C songs[]", ""]
    levels = ROOT / "build" / "levels" / "wl6"
    for n in range(60):
        ep, slot = n // 10, n % 10
        name = f"Wolf{ep + 1} Map{slot + 1}"
        f = levels / f"MAP{n:02d}.json"
        if f.exists():
            name = json.loads(f.read_text())["name"]
        mapname = f"MAP{n + 1:02d}"
        lines.append(f'map {mapname} "{name}"')
        lines.append("{")
        lines.append(f"    levelnum = {n + 1}")
        lines.append(f'    music = "{EP_SONGS[ep][slot]}"')
        lines.append("}")
        lines.append("")
    (ROOT / "src" / "mapinfo_maps.txt").write_text("\n".join(lines) + "\n")
    print("generated mapinfo_maps.txt (60 maps)")


if __name__ == "__main__":
    main()
