#!/usr/bin/env python3
"""Generate src/mapinfo_maps.txt: all 60 WL6 map defs with names, levelnums,
and per-level music from the songs[] table (WL_PLAY.C:107-199).

Music lump names are the track names minus _MUS (all <= 8 chars), matching
make_assets' music copies.
"""
from pathlib import Path
import json

ROOT = Path(__file__).resolve().parent.parent

# songs[] per episode slot (WL_PLAY.C): 10 slots x 6 episodes
# ElevatorBackTo[] (WL_GAME.C:39): 0-based mapon the secret floor returns to
ELEVATOR_BACK_TO = [1, 1, 7, 3, 5, 3]

# par times (TALLY-001): the source stores minutes; MAPINFO wants seconds
PAR = json.loads((ROOT / "docs" / "data" / "par_times.json").read_text())["wl6"]

EP_SONGS = [
    ["GETTHEM", "SEARCHN", "POW", "SUSPENSE", "GETTHEM", "SEARCHN", "POW",
     "SUSPENSE", "WARMARCH", "CORNER"],
    ["NAZI_OMI", "PREGNANT", "GOINGAFT", "HEADACHE", "NAZI_OMI", "PREGNANT",
     "HEADACHE", "GOINGAFT", "WARMARCH", "DUNGEON"],
    ["INTROCW3", "NAZI_RAP", "TWELFTH", "ZEROHOUR", "INTROCW3", "NAZI_RAP",
     "TWELFTH", "ZEROHOUR", "ULTIMATE", "PACMAN"],
    ["GETTHEM", "SEARCHN", "POW", "SUSPENSE", "GETTHEM", "SEARCHN", "POW",
     "SUSPENSE", "WARMARCH", "CORNER"],
    ["NAZI_OMI", "PREGNANT", "GOINGAFT", "HEADACHE", "NAZI_OMI", "PREGNANT",
     "HEADACHE", "GOINGAFT", "WARMARCH", "DUNGEON"],
    ["INTROCW3", "NAZI_RAP", "TWELFTH", "ZEROHOUR", "INTROCW3", "NAZI_RAP",
     "TWELFTH", "ZEROHOUR", "ULTIMATE", "FUNKYOU"],
]


def main():
    lines = ["// GENERATED by tools/gen_mapinfo.py — included from MAPINFO",
             "// Map names from GAMEMAPS; music per WL_PLAY.C songs[]", ""]
    levels = ROOT / "build" / "levels" / "wl6"
    cj = ROOT / "docs" / "data" / "ceiling_colors.json"
    ceilings = None
    if cj.exists():
        ceilings = json.loads(cj.read_text())["wl6"]     # list, one per map
    for n in range(60):
        ep, slot = n // 10, n % 10
        name = f"Wolf{ep + 1} Map{slot + 1}"
        f = levels / f"MAP{n:02d}.json"
        if f.exists():
            name = json.loads(f.read_text())["name"]
        mapname = f"MAP{n + 1:02d}"
        # progression (WL_GAME.C:1386-1400): floors 1-8 advance in order;
        # the secret floor (slot 9) returns to ElevatorBackTo[episode];
        # the boss floor (slot 8) ends the episode via the victory tile.
        if slot == 9:
            nxt = ep * 10 + ELEVATOR_BACK_TO[ep] + 1
        elif slot == 8:
            nxt = -1                        # boss floor: the episode ends
        else:
            nxt = n + 2
        secret = ep * 10 + 10               # slot 9 of this episode
        lines.append(f'map {mapname} "{name}"')
        lines.append("{")
        lines.append(f"    levelnum = {n + 1}")
        lines.append(f'    music = "{EP_SONGS[ep][slot]}"')
        # sky = the level's own solid ceiling colour. Ceilings become
        # F_SKY1 while anyone is in third person (skyceil.zs) so the
        # chase camera can rise above the map; a sky that IS the ceiling
        # colour makes the swap invisible from below.
        if ceilings is not None:
            lines.append(f'    sky1 = "CEIL{ceilings[n]:02X}"')
        if nxt < 0:
            # The boss floor ends the episode. It cannot use MAPINFO's
            # "EndTitle" or an endgame block: EndTitle skips the
            # intermission (which is where Victory() draws the episode
            # averages) and the endgame block is rejected by the parser.
            # So the floor keeps a placeholder next and WolfIntermission
            # takes over in victoryMode; the real chain out of it
            # (EndText -> high scores -> title) lands there.
            # the ending returns to the title map (attract -> menu);
            # a placeholder next of floor 1 loaded a broken 'next level'
            # with the victory freeze still on the player
            lines.append('    next = "TITLEMAP"')
        else:
            lines.append(f'    next = "MAP{nxt:02d}"')
        lines.append(f'    secretnext = "MAP{secret:02d}"')
        lines.append(f"    par = {int(round(PAR[n]['minutes'] * 60))}")
        lines.append("}")
        lines.append("")
    (ROOT / "src" / "mapinfo_maps.txt").write_text("\n".join(lines) + "\n")
    print("generated mapinfo_maps.txt (60 maps)")
    gen_spear()


# Spear of Destiny: ONE linear 21-floor campaign, no episode select and
# no secret-floor returns - floors 19/20 are the secret levels and 21 is
# the Angel of Death. Songs are the SPEAR tail of WL_PLAY.C's songs[].
SOD_SONGS = ["XTIPTOE", "XFUNKIE", "XDEATH", "XGETYOU", "ULTIMATE",
             "DUNGEON", "GOINGAFT", "POW", "TWELFTH", "ULTIMATE",
             "NAZI_OMI", "GETTHEM", "SUSPENSE", "SEARCHN", "ZEROHOUR",
             "ULTIMATE", "XPUTIT", "ULTIMATE", "XJAZNAZI", "XFUNKIE",
             "XEVIL"]


def gen_spear():
    pars = json.loads((ROOT / "docs" / "data"
                       / "par_times.json").read_text())["sod"]
    sod_ceil = json.loads((ROOT / "docs" / "data"
                           / "ceiling_colors.json").read_text())["sod"]
    levels = ROOT / "build" / "levels" / "sod"
    lines = ["// GENERATED by tools/gen_mapinfo.py - included from",
             "// MAPINFO.spear. Spear of Destiny: 21 linear floors.", ""]
    for n in range(21):
        name = "Spear Map%d" % (n + 1)
        f = levels / ("MAP%02d.json" % n)
        if f.exists():
            name = json.loads(f.read_text())["name"]
        lines.append('map MAP%02d "%s"' % (n + 1, name))
        lines.append("{")
        lines.append("    levelnum = %d" % (n + 1))
        lines.append('    music = "%s"' % SOD_SONGS[n])
        lines.append('    sky1 = "CEIL%02X"' % sod_ceil[n])
        if n == 20:
            lines.append('    next = "TITLEMAP"')   # A_Victory ends Spear
        else:
            lines.append('    next = "MAP%02d"' % (n + 2))
        par = pars[n]["minutes"] if n < len(pars) else 0
        lines.append("    par = %d" % int(round(par * 60)))
        lines.append("}")
        lines.append("")
    (ROOT / "src" / "mapinfo_sod.txt").write_text(
        chr(10).join(lines) + chr(10))
    print("generated mapinfo_sod.txt (21 maps)")


if __name__ == "__main__":
    main()
