// GENERATED by tools/gen_enemies.py from docs/data/state_tables.json
// Rows are WL_ACT2.C statetype entries, one to one. Do not edit.

class WolfGuardTable
{
    const GRDSTAND = 0;
    const GRDPATH1 = 1;
    const GRDPATH1S = 2;
    const GRDPATH2 = 3;
    const GRDPATH3 = 4;
    const GRDPATH3S = 5;
    const GRDPATH4 = 6;
    const GRDPAIN = 7;
    const GRDPAIN1 = 8;
    const GRDSHOOT1 = 9;
    const GRDSHOOT2 = 10;
    const GRDSHOOT3 = 11;
    const GRDCHASE1 = 12;
    const GRDCHASE1S = 13;
    const GRDCHASE2 = 14;
    const GRDCHASE3 = 15;
    const GRDCHASE3S = 16;
    const GRDCHASE4 = 17;
    const GRDDIE1 = 18;
    const GRDDIE2 = 19;
    const GRDDIE3 = 20;
    const GRDDIE4 = 21;
    static const int ROT[] = { 1, 1, 1, 1, 1, 1, 1, 2, 2, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0 };
    static const String SPR[] = { "GRDS", "GRDW", "GRDW", "GRDW", "GRDW", "GRDW", "GRDW", "GRDP", "GRDP", "GRDA", "GRDA", "GRDA", "GRDW", "GRDW", "GRDW", "GRDW", "GRDW", "GRDW", "GRDD", "GRDD", "GRDD", "SDED" };
    static const int FRM[] = { 0, 0, 0, 1, 2, 2, 3, 0, 1, 0, 1, 2, 0, 0, 1, 2, 2, 3, 0, 1, 2, 0 };
    static const int TICS[] = { 0, 20, 5, 15, 20, 5, 15, 10, 10, 20, 20, 20, 10, 3, 8, 10, 3, 8, 15, 15, 15, 0 };
    static const int THINK[] = { 1, 2, 0, 2, 2, 0, 2, 0, 0, 0, 0, 0, 3, 0, 3, 3, 0, 3, 0, 0, 0, 0 };
    static const int ACT[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 10, 0, 0, 0 };
    static const int NEXT[] = { 0, 2, 3, 4, 5, 6, 1, 12, 12, 10, 11, 12, 13, 14, 15, 16, 17, 12, 19, 20, 21, 21 };
}

