// GENERATED by tools/gen_statics.py from docs/data/statinfo.json
// (both game sets). Do not edit; rerun the tool.

// ---------------- wl6 statics ----------------

// statinfo[0] sprite SPR_STAT_0: puddle          spr1v
class WolfStatic00 : Actor
{
    Default
    {
        +NOBLOCKMAP
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S000 A -1;
        Stop;
    }
}

// statinfo[1] sprite SPR_STAT_1: Green Barrel    "
class WolfStatic01 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S001 A -1;
        Stop;
    }
}

// statinfo[2] sprite SPR_STAT_2: Table/chairs    "
class WolfStatic02 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S002 A -1;
        Stop;
    }
}

// statinfo[3] sprite SPR_STAT_3: Floor lamp      "
class WolfStatic03 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S003 A -1;
        Stop;
    }
}

// statinfo[4] sprite SPR_STAT_4: Chandelier      "
class WolfStatic04 : Actor
{
    Default
    {
        +NOBLOCKMAP
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S004 A -1;
        Stop;
    }
}

// statinfo[5] sprite SPR_STAT_5: Hanged man      "
class WolfStatic05 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S005 A -1;
        Stop;
    }
}

// statinfo[6] sprite SPR_STAT_6: Bad food        "
class WolfStatic06 : WolfPickup
{
    States
    {
    Spawn:
        S006 A -1;
        Stop;
    }
    override int BonusKind() { return WolfPickup.BO_ALPO; }
}

// statinfo[7] sprite SPR_STAT_7: Red pillar      "
class WolfStatic07 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S007 A -1;
        Stop;
    }
}

// statinfo[8] sprite SPR_STAT_8: Tree            spr2v
class WolfStatic08 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S008 A -1;
        Stop;
    }
}

// statinfo[9] sprite SPR_STAT_9: Skeleton flat   "
class WolfStatic09 : Actor
{
    Default
    {
        +NOBLOCKMAP
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S009 A -1;
        Stop;
    }
}

// statinfo[10] sprite SPR_STAT_10: Sink            " (SOD:gibs)
class WolfStatic10 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S010 A -1;
        Stop;
    }
}

// statinfo[11] sprite SPR_STAT_11: Potted plant    "
class WolfStatic11 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S011 A -1;
        Stop;
    }
}

// statinfo[12] sprite SPR_STAT_12: Urn             "
class WolfStatic12 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S012 A -1;
        Stop;
    }
}

// statinfo[13] sprite SPR_STAT_13: Bare table      "
class WolfStatic13 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S013 A -1;
        Stop;
    }
}

// statinfo[14] sprite SPR_STAT_14: Ceiling light   "
class WolfStatic14 : Actor
{
    Default
    {
        +NOBLOCKMAP
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S014 A -1;
        Stop;
    }
}

// statinfo[15] sprite SPR_STAT_15: Kitchen stuff   "
class WolfStatic15 : Actor
{
    Default
    {
        +NOBLOCKMAP
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S015 A -1;
        Stop;
    }
}

// statinfo[16] sprite SPR_STAT_16: suit of armor   spr3v
class WolfStatic16 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S016 A -1;
        Stop;
    }
}

// statinfo[17] sprite SPR_STAT_17: Hanging cage    "
class WolfStatic17 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S017 A -1;
        Stop;
    }
}

// statinfo[18] sprite SPR_STAT_18: SkeletoninCage  "
class WolfStatic18 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S018 A -1;
        Stop;
    }
}

// statinfo[19] sprite SPR_STAT_19: Skeleton relax  "
class WolfStatic19 : Actor
{
    Default
    {
        +NOBLOCKMAP
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S019 A -1;
        Stop;
    }
}

// statinfo[20] sprite SPR_STAT_20: Key 1           "
class WolfStatic20 : WolfPickup
{
    States
    {
    Spawn:
        S020 A -1;
        Stop;
    }
    override int BonusKind() { return WolfPickup.BO_KEY1; }
}

// statinfo[21] sprite SPR_STAT_21: Key 2           "
class WolfStatic21 : WolfPickup
{
    States
    {
    Spawn:
        S021 A -1;
        Stop;
    }
    override int BonusKind() { return WolfPickup.BO_KEY2; }
}

// statinfo[22] sprite SPR_STAT_22: stuff				(SOD:gibs)
class WolfStatic22 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S022 A -1;
        Stop;
    }
}

// statinfo[23] sprite SPR_STAT_23: stuff
class WolfStatic23 : Actor
{
    Default
    {
        +NOBLOCKMAP
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S023 A -1;
        Stop;
    }
}

// statinfo[24] sprite SPR_STAT_24: Good food       spr4v
class WolfStatic24 : WolfPickup
{
    States
    {
    Spawn:
        S024 A -1;
        Stop;
    }
    override int BonusKind() { return WolfPickup.BO_FOOD; }
}

// statinfo[25] sprite SPR_STAT_25: First aid       "
class WolfStatic25 : WolfPickup
{
    States
    {
    Spawn:
        S025 A -1;
        Stop;
    }
    override int BonusKind() { return WolfPickup.BO_FIRSTAID; }
}

// statinfo[26] sprite SPR_STAT_26: Clip            "
class WolfStatic26 : WolfPickup
{
    States
    {
    Spawn:
        S026 A -1;
        Stop;
    }
    override int BonusKind() { return WolfPickup.BO_CLIP; }
}

// statinfo[27] sprite SPR_STAT_27: Machine gun     "
class WolfStatic27 : WolfPickup
{
    States
    {
    Spawn:
        S027 A -1;
        Stop;
    }
    override int BonusKind() { return WolfPickup.BO_MACHINEGUN; }
}

// statinfo[28] sprite SPR_STAT_28: Gatling gun     "
class WolfStatic28 : WolfPickup
{
    States
    {
    Spawn:
        S028 A -1;
        Stop;
    }
    override int BonusKind() { return WolfPickup.BO_CHAINGUN; }
}

// statinfo[29] sprite SPR_STAT_29: Cross           "
class WolfStatic29 : WolfPickup
{
    States
    {
    Spawn:
        S029 A -1;
        Stop;
    }
    override int BonusKind() { return WolfPickup.BO_CROSS; }
}

// statinfo[30] sprite SPR_STAT_30: Chalice         "
class WolfStatic30 : WolfPickup
{
    States
    {
    Spawn:
        S030 A -1;
        Stop;
    }
    override int BonusKind() { return WolfPickup.BO_CHALICE; }
}

// statinfo[31] sprite SPR_STAT_31: Bible           "
class WolfStatic31 : WolfPickup
{
    States
    {
    Spawn:
        S031 A -1;
        Stop;
    }
    override int BonusKind() { return WolfPickup.BO_BIBLE; }
}

// statinfo[32] sprite SPR_STAT_32: crown           spr5v
class WolfStatic32 : WolfPickup
{
    States
    {
    Spawn:
        S032 A -1;
        Stop;
    }
    override int BonusKind() { return WolfPickup.BO_CROWN; }
}

// statinfo[33] sprite SPR_STAT_33: one up          "
class WolfStatic33 : WolfPickup
{
    States
    {
    Spawn:
        S033 A -1;
        Stop;
    }
    override int BonusKind() { return WolfPickup.BO_FULLHEAL; }
}

// statinfo[34] sprite SPR_STAT_34: gibs            "
class WolfStatic34 : WolfPickup
{
    States
    {
    Spawn:
        S034 A -1;
        Stop;
    }
    override int BonusKind() { return WolfPickup.BO_GIBS; }
}

// statinfo[35] sprite SPR_STAT_35: barrel          "
class WolfStatic35 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S035 A -1;
        Stop;
    }
}

// statinfo[36] sprite SPR_STAT_36: well            "
class WolfStatic36 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S036 A -1;
        Stop;
    }
}

// statinfo[37] sprite SPR_STAT_37: Empty well      "
class WolfStatic37 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S037 A -1;
        Stop;
    }
}

// statinfo[38] sprite SPR_STAT_38: Gibs 2          "
class WolfStatic38 : WolfPickup
{
    States
    {
    Spawn:
        S038 A -1;
        Stop;
    }
    override int BonusKind() { return WolfPickup.BO_GIBS; }
}

// statinfo[39] sprite SPR_STAT_39: flag				"
class WolfStatic39 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S039 A -1;
        Stop;
    }
}

// statinfo[40] sprite SPR_STAT_40: Call Apogee		spr7v
class WolfStatic40 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S040 A -1;
        Stop;
    }
}

// statinfo[41] sprite SPR_STAT_41: junk            "
class WolfStatic41 : Actor
{
    Default
    {
        +NOBLOCKMAP
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S041 A -1;
        Stop;
    }
}

// statinfo[42] sprite SPR_STAT_42: junk 		   "
class WolfStatic42 : Actor
{
    Default
    {
        +NOBLOCKMAP
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S042 A -1;
        Stop;
    }
}

// statinfo[43] sprite SPR_STAT_43: junk            "
class WolfStatic43 : Actor
{
    Default
    {
        +NOBLOCKMAP
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S043 A -1;
        Stop;
    }
}

// statinfo[44] sprite SPR_STAT_44: pots            "
class WolfStatic44 : Actor
{
    Default
    {
        +NOBLOCKMAP
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S044 A -1;
        Stop;
    }
}

// statinfo[45] sprite SPR_STAT_45: stove           " (SOD:gibs)
class WolfStatic45 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S045 A -1;
        Stop;
    }
}

// statinfo[46] sprite SPR_STAT_46: spears          " (SOD:gibs)
class WolfStatic46 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S046 A -1;
        Stop;
    }
}

// statinfo[47] sprite SPR_STAT_47: vines			"
class WolfStatic47 : Actor
{
    Default
    {
        +NOBLOCKMAP
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S047 A -1;
        Stop;
    }
}

// statinfo[48] sprite SPR_STAT_26: Clip            "
class WolfStatic48 : WolfPickup
{
    States
    {
    Spawn:
        S048 A -1;
        Stop;
    }
    override int BonusKind() { return WolfPickup.BO_CLIP2; }
}

// ---------------- sod statics ----------------

// statinfo[0] sprite SPR_STAT_0: puddle          spr1v
class SodStatic00 : Actor
{
    Default
    {
        +NOBLOCKMAP
        +NOGRAVITY
    }
    States
    {
    Spawn:
        D000 A -1;
        Stop;
    }
}

// statinfo[1] sprite SPR_STAT_1: Green Barrel    "
class SodStatic01 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        D001 A -1;
        Stop;
    }
}

// statinfo[2] sprite SPR_STAT_2: Table/chairs    "
class SodStatic02 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        D002 A -1;
        Stop;
    }
}

// statinfo[3] sprite SPR_STAT_3: Floor lamp      "
class SodStatic03 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        D003 A -1;
        Stop;
    }
}

// statinfo[4] sprite SPR_STAT_4: Chandelier      "
class SodStatic04 : Actor
{
    Default
    {
        +NOBLOCKMAP
        +NOGRAVITY
    }
    States
    {
    Spawn:
        D004 A -1;
        Stop;
    }
}

// statinfo[5] sprite SPR_STAT_5: Hanged man      "
class SodStatic05 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        D005 A -1;
        Stop;
    }
}

// statinfo[6] sprite SPR_STAT_6: Bad food        "
class SodStatic06 : WolfPickup
{
    States
    {
    Spawn:
        D006 A -1;
        Stop;
    }
    override int BonusKind() { return WolfPickup.BO_ALPO; }
}

// statinfo[7] sprite SPR_STAT_7: Red pillar      "
class SodStatic07 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        D007 A -1;
        Stop;
    }
}

// statinfo[8] sprite SPR_STAT_8: Tree            spr2v
class SodStatic08 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        D008 A -1;
        Stop;
    }
}

// statinfo[9] sprite SPR_STAT_9: Skeleton flat   "
class SodStatic09 : Actor
{
    Default
    {
        +NOBLOCKMAP
        +NOGRAVITY
    }
    States
    {
    Spawn:
        D009 A -1;
        Stop;
    }
}

// statinfo[10] sprite SPR_STAT_10: Sink            " (SOD:gibs)
class SodStatic10 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        D010 A -1;
        Stop;
    }
}

// statinfo[11] sprite SPR_STAT_11: Potted plant    "
class SodStatic11 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        D011 A -1;
        Stop;
    }
}

// statinfo[12] sprite SPR_STAT_12: Urn             "
class SodStatic12 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        D012 A -1;
        Stop;
    }
}

// statinfo[13] sprite SPR_STAT_13: Bare table      "
class SodStatic13 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        D013 A -1;
        Stop;
    }
}

// statinfo[14] sprite SPR_STAT_14: Ceiling light   "
class SodStatic14 : Actor
{
    Default
    {
        +NOBLOCKMAP
        +NOGRAVITY
    }
    States
    {
    Spawn:
        D014 A -1;
        Stop;
    }
}

// statinfo[15] sprite SPR_STAT_15: Gibs!
class SodStatic15 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        D015 A -1;
        Stop;
    }
}

// statinfo[16] sprite SPR_STAT_16: suit of armor   spr3v
class SodStatic16 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        D016 A -1;
        Stop;
    }
}

// statinfo[17] sprite SPR_STAT_17: Hanging cage    "
class SodStatic17 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        D017 A -1;
        Stop;
    }
}

// statinfo[18] sprite SPR_STAT_18: SkeletoninCage  "
class SodStatic18 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        D018 A -1;
        Stop;
    }
}

// statinfo[19] sprite SPR_STAT_19: Skeleton relax  "
class SodStatic19 : Actor
{
    Default
    {
        +NOBLOCKMAP
        +NOGRAVITY
    }
    States
    {
    Spawn:
        D019 A -1;
        Stop;
    }
}

// statinfo[20] sprite SPR_STAT_20: Key 1           "
class SodStatic20 : WolfPickup
{
    States
    {
    Spawn:
        D020 A -1;
        Stop;
    }
    override int BonusKind() { return WolfPickup.BO_KEY1; }
}

// statinfo[21] sprite SPR_STAT_21: Key 2           "
class SodStatic21 : WolfPickup
{
    States
    {
    Spawn:
        D021 A -1;
        Stop;
    }
    override int BonusKind() { return WolfPickup.BO_KEY2; }
}

// statinfo[22] sprite SPR_STAT_22: stuff				(SOD:gibs)
class SodStatic22 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        D022 A -1;
        Stop;
    }
}

// statinfo[23] sprite SPR_STAT_23: stuff
class SodStatic23 : Actor
{
    Default
    {
        +NOBLOCKMAP
        +NOGRAVITY
    }
    States
    {
    Spawn:
        D023 A -1;
        Stop;
    }
}

// statinfo[24] sprite SPR_STAT_24: Good food       spr4v
class SodStatic24 : WolfPickup
{
    States
    {
    Spawn:
        D024 A -1;
        Stop;
    }
    override int BonusKind() { return WolfPickup.BO_FOOD; }
}

// statinfo[25] sprite SPR_STAT_25: First aid       "
class SodStatic25 : WolfPickup
{
    States
    {
    Spawn:
        D025 A -1;
        Stop;
    }
    override int BonusKind() { return WolfPickup.BO_FIRSTAID; }
}

// statinfo[26] sprite SPR_STAT_26: Clip            "
class SodStatic26 : WolfPickup
{
    States
    {
    Spawn:
        D026 A -1;
        Stop;
    }
    override int BonusKind() { return WolfPickup.BO_CLIP; }
}

// statinfo[27] sprite SPR_STAT_27: Machine gun     "
class SodStatic27 : WolfPickup
{
    States
    {
    Spawn:
        D027 A -1;
        Stop;
    }
    override int BonusKind() { return WolfPickup.BO_MACHINEGUN; }
}

// statinfo[28] sprite SPR_STAT_28: Gatling gun     "
class SodStatic28 : WolfPickup
{
    States
    {
    Spawn:
        D028 A -1;
        Stop;
    }
    override int BonusKind() { return WolfPickup.BO_CHAINGUN; }
}

// statinfo[29] sprite SPR_STAT_29: Cross           "
class SodStatic29 : WolfPickup
{
    States
    {
    Spawn:
        D029 A -1;
        Stop;
    }
    override int BonusKind() { return WolfPickup.BO_CROSS; }
}

// statinfo[30] sprite SPR_STAT_30: Chalice         "
class SodStatic30 : WolfPickup
{
    States
    {
    Spawn:
        D030 A -1;
        Stop;
    }
    override int BonusKind() { return WolfPickup.BO_CHALICE; }
}

// statinfo[31] sprite SPR_STAT_31: Bible           "
class SodStatic31 : WolfPickup
{
    States
    {
    Spawn:
        D031 A -1;
        Stop;
    }
    override int BonusKind() { return WolfPickup.BO_BIBLE; }
}

// statinfo[32] sprite SPR_STAT_32: crown           spr5v
class SodStatic32 : WolfPickup
{
    States
    {
    Spawn:
        D032 A -1;
        Stop;
    }
    override int BonusKind() { return WolfPickup.BO_CROWN; }
}

// statinfo[33] sprite SPR_STAT_33: one up          "
class SodStatic33 : WolfPickup
{
    States
    {
    Spawn:
        D033 A -1;
        Stop;
    }
    override int BonusKind() { return WolfPickup.BO_FULLHEAL; }
}

// statinfo[34] sprite SPR_STAT_34: gibs            "
class SodStatic34 : WolfPickup
{
    States
    {
    Spawn:
        D034 A -1;
        Stop;
    }
    override int BonusKind() { return WolfPickup.BO_GIBS; }
}

// statinfo[35] sprite SPR_STAT_35: barrel          "
class SodStatic35 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        D035 A -1;
        Stop;
    }
}

// statinfo[36] sprite SPR_STAT_36: well            "
class SodStatic36 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        D036 A -1;
        Stop;
    }
}

// statinfo[37] sprite SPR_STAT_37: Empty well      "
class SodStatic37 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        D037 A -1;
        Stop;
    }
}

// statinfo[38] sprite SPR_STAT_38: Gibs 2          "
class SodStatic38 : WolfPickup
{
    States
    {
    Spawn:
        D038 A -1;
        Stop;
    }
    override int BonusKind() { return WolfPickup.BO_GIBS; }
}

// statinfo[39] sprite SPR_STAT_39: flag				"
class SodStatic39 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        D039 A -1;
        Stop;
    }
}

// statinfo[40] sprite SPR_STAT_40: Red light
class SodStatic40 : Actor
{
    Default
    {
        +NOBLOCKMAP
        +NOGRAVITY
    }
    States
    {
    Spawn:
        D040 A -1;
        Stop;
    }
}

// statinfo[41] sprite SPR_STAT_41: junk            "
class SodStatic41 : Actor
{
    Default
    {
        +NOBLOCKMAP
        +NOGRAVITY
    }
    States
    {
    Spawn:
        D041 A -1;
        Stop;
    }
}

// statinfo[42] sprite SPR_STAT_42: junk 		   "
class SodStatic42 : Actor
{
    Default
    {
        +NOBLOCKMAP
        +NOGRAVITY
    }
    States
    {
    Spawn:
        D042 A -1;
        Stop;
    }
}

// statinfo[43] sprite SPR_STAT_43: junk            "
class SodStatic43 : Actor
{
    Default
    {
        +NOBLOCKMAP
        +NOGRAVITY
    }
    States
    {
    Spawn:
        D043 A -1;
        Stop;
    }
}

// statinfo[44] sprite SPR_STAT_44: Gibs!
class SodStatic44 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        D044 A -1;
        Stop;
    }
}

// statinfo[45] sprite SPR_STAT_45: stove           " (SOD:gibs)
class SodStatic45 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        D045 A -1;
        Stop;
    }
}

// statinfo[46] sprite SPR_STAT_46: spears          " (SOD:gibs)
class SodStatic46 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        D046 A -1;
        Stop;
    }
}

// statinfo[47] sprite SPR_STAT_47: vines			"
class SodStatic47 : Actor
{
    Default
    {
        +NOBLOCKMAP
        +NOGRAVITY
    }
    States
    {
    Spawn:
        D047 A -1;
        Stop;
    }
}

// statinfo[48] sprite SPR_STAT_48: marble pillar
class SodStatic48 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        D048 A -1;
        Stop;
    }
}

// statinfo[49] sprite SPR_STAT_49: bonus 25 clip
class SodStatic49 : WolfPickup
{
    States
    {
    Spawn:
        D049 A -1;
        Stop;
    }
    override int BonusKind() { return WolfPickup.BO_25CLIP; }
}

// statinfo[50] sprite SPR_STAT_50: truck
class SodStatic50 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        D050 A -1;
        Stop;
    }
}

// statinfo[51] sprite SPR_STAT_51: SPEAR OF DESTINY!
class SodStatic51 : Actor
{
    Default
    {
        +NOBLOCKMAP
        +NOGRAVITY
    }
    States
    {
    Spawn:
        D051 A -1;
        Stop;
    }
}

// statinfo[52] sprite SPR_STAT_26: Clip            "
class SodStatic52 : WolfPickup
{
    States
    {
    Spawn:
        D052 A -1;
        Stop;
    }
    override int BonusKind() { return WolfPickup.BO_CLIP2; }
}

// dead guard (map code 124, MAP-004): SPR_GRD_DEAD, inert
class WolfDeadGuard : Actor
{
    Default
    {
        +NOBLOCKMAP
        +NOGRAVITY
    }
    States
    {
    Spawn:
        SDED A -1;
        Stop;
    }
}

