// GENERATED by tools/gen_statics.py from docs/data/statinfo.json
// (WL6 build). Do not edit; rerun the tool.

// statinfo[0] sprite SPR_STAT_0: puddle          spr1v
class WolfStatic00 : Actor
{
    Default
    {
        +NOBLOCKMAP
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S000 A -1;
        Stop;
    }
}

// statinfo[1] sprite SPR_STAT_1: Green Barrel    "
class WolfStatic01 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S001 A -1;
        Stop;
    }
}

// statinfo[2] sprite SPR_STAT_2: Table/chairs    "
class WolfStatic02 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S002 A -1;
        Stop;
    }
}

// statinfo[3] sprite SPR_STAT_3: Floor lamp      "
class WolfStatic03 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S003 A -1;
        Stop;
    }
}

// statinfo[4] sprite SPR_STAT_4: Chandelier      "
class WolfStatic04 : Actor
{
    Default
    {
        +NOBLOCKMAP
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S004 A -1;
        Stop;
    }
}

// statinfo[5] sprite SPR_STAT_5: Hanged man      "
class WolfStatic05 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S005 A -1;
        Stop;
    }
}

// statinfo[6] sprite SPR_STAT_6: Bad food        "  // TODO Phase 2 pickup: bo_alpo
class WolfStatic06 : Actor
{
    Default
    {
        +NOBLOCKMAP
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S006 A -1;
        Stop;
    }
}

// statinfo[7] sprite SPR_STAT_7: Red pillar      "
class WolfStatic07 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S007 A -1;
        Stop;
    }
}

// statinfo[8] sprite SPR_STAT_8: Tree            spr2v
class WolfStatic08 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S008 A -1;
        Stop;
    }
}

// statinfo[9] sprite SPR_STAT_9: Skeleton flat   "
class WolfStatic09 : Actor
{
    Default
    {
        +NOBLOCKMAP
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S009 A -1;
        Stop;
    }
}

// statinfo[10] sprite SPR_STAT_10: Sink            " (SOD:gibs)
class WolfStatic10 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S010 A -1;
        Stop;
    }
}

// statinfo[11] sprite SPR_STAT_11: Potted plant    "
class WolfStatic11 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S011 A -1;
        Stop;
    }
}

// statinfo[12] sprite SPR_STAT_12: Urn             "
class WolfStatic12 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S012 A -1;
        Stop;
    }
}

// statinfo[13] sprite SPR_STAT_13: Bare table      "
class WolfStatic13 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S013 A -1;
        Stop;
    }
}

// statinfo[14] sprite SPR_STAT_14: Ceiling light   "
class WolfStatic14 : Actor
{
    Default
    {
        +NOBLOCKMAP
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S014 A -1;
        Stop;
    }
}

// statinfo[15] sprite SPR_STAT_15: Kitchen stuff   "
class WolfStatic15 : Actor
{
    Default
    {
        +NOBLOCKMAP
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S015 A -1;
        Stop;
    }
}

// statinfo[16] sprite SPR_STAT_16: suit of armor   spr3v
class WolfStatic16 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S016 A -1;
        Stop;
    }
}

// statinfo[17] sprite SPR_STAT_17: Hanging cage    "
class WolfStatic17 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S017 A -1;
        Stop;
    }
}

// statinfo[18] sprite SPR_STAT_18: SkeletoninCage  "
class WolfStatic18 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S018 A -1;
        Stop;
    }
}

// statinfo[19] sprite SPR_STAT_19: Skeleton relax  "
class WolfStatic19 : Actor
{
    Default
    {
        +NOBLOCKMAP
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S019 A -1;
        Stop;
    }
}

// statinfo[20] sprite SPR_STAT_20: Key 1           "  // TODO Phase 2 pickup: bo_key1
class WolfStatic20 : Actor
{
    Default
    {
        +NOBLOCKMAP
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S020 A -1;
        Stop;
    }
}

// statinfo[21] sprite SPR_STAT_21: Key 2           "  // TODO Phase 2 pickup: bo_key2
class WolfStatic21 : Actor
{
    Default
    {
        +NOBLOCKMAP
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S021 A -1;
        Stop;
    }
}

// statinfo[22] sprite SPR_STAT_22: stuff				(SOD:gibs)
class WolfStatic22 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S022 A -1;
        Stop;
    }
}

// statinfo[23] sprite SPR_STAT_23: stuff
class WolfStatic23 : Actor
{
    Default
    {
        +NOBLOCKMAP
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S023 A -1;
        Stop;
    }
}

// statinfo[24] sprite SPR_STAT_24: Good food       spr4v  // TODO Phase 2 pickup: bo_food
class WolfStatic24 : Actor
{
    Default
    {
        +NOBLOCKMAP
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S024 A -1;
        Stop;
    }
}

// statinfo[25] sprite SPR_STAT_25: First aid       "  // TODO Phase 2 pickup: bo_firstaid
class WolfStatic25 : Actor
{
    Default
    {
        +NOBLOCKMAP
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S025 A -1;
        Stop;
    }
}

// statinfo[26] sprite SPR_STAT_26: Clip            "  // TODO Phase 2 pickup: bo_clip
class WolfStatic26 : Actor
{
    Default
    {
        +NOBLOCKMAP
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S026 A -1;
        Stop;
    }
}

// statinfo[27] sprite SPR_STAT_27: Machine gun     "  // TODO Phase 2 pickup: bo_machinegun
class WolfStatic27 : Actor
{
    Default
    {
        +NOBLOCKMAP
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S027 A -1;
        Stop;
    }
}

// statinfo[28] sprite SPR_STAT_28: Gatling gun     "  // TODO Phase 2 pickup: bo_chaingun
class WolfStatic28 : Actor
{
    Default
    {
        +NOBLOCKMAP
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S028 A -1;
        Stop;
    }
}

// statinfo[29] sprite SPR_STAT_29: Cross           "  // TODO Phase 2 pickup: bo_cross
class WolfStatic29 : Actor
{
    Default
    {
        +NOBLOCKMAP
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S029 A -1;
        Stop;
    }
}

// statinfo[30] sprite SPR_STAT_30: Chalice         "  // TODO Phase 2 pickup: bo_chalice
class WolfStatic30 : Actor
{
    Default
    {
        +NOBLOCKMAP
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S030 A -1;
        Stop;
    }
}

// statinfo[31] sprite SPR_STAT_31: Bible           "  // TODO Phase 2 pickup: bo_bible
class WolfStatic31 : Actor
{
    Default
    {
        +NOBLOCKMAP
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S031 A -1;
        Stop;
    }
}

// statinfo[32] sprite SPR_STAT_32: crown           spr5v  // TODO Phase 2 pickup: bo_crown
class WolfStatic32 : Actor
{
    Default
    {
        +NOBLOCKMAP
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S032 A -1;
        Stop;
    }
}

// statinfo[33] sprite SPR_STAT_33: one up          "  // TODO Phase 2 pickup: bo_fullheal
class WolfStatic33 : Actor
{
    Default
    {
        +NOBLOCKMAP
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S033 A -1;
        Stop;
    }
}

// statinfo[34] sprite SPR_STAT_34: gibs            "  // TODO Phase 2 pickup: bo_gibs
class WolfStatic34 : Actor
{
    Default
    {
        +NOBLOCKMAP
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S034 A -1;
        Stop;
    }
}

// statinfo[35] sprite SPR_STAT_35: barrel          "
class WolfStatic35 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S035 A -1;
        Stop;
    }
}

// statinfo[36] sprite SPR_STAT_36: well            "
class WolfStatic36 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S036 A -1;
        Stop;
    }
}

// statinfo[37] sprite SPR_STAT_37: Empty well      "
class WolfStatic37 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S037 A -1;
        Stop;
    }
}

// statinfo[38] sprite SPR_STAT_38: Gibs 2          "  // TODO Phase 2 pickup: bo_gibs
class WolfStatic38 : Actor
{
    Default
    {
        +NOBLOCKMAP
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S038 A -1;
        Stop;
    }
}

// statinfo[39] sprite SPR_STAT_39: flag				"
class WolfStatic39 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S039 A -1;
        Stop;
    }
}

// statinfo[40] sprite SPR_STAT_40: Call Apogee		spr7v
class WolfStatic40 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S040 A -1;
        Stop;
    }
}

// statinfo[41] sprite SPR_STAT_41: junk            "
class WolfStatic41 : Actor
{
    Default
    {
        +NOBLOCKMAP
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S041 A -1;
        Stop;
    }
}

// statinfo[42] sprite SPR_STAT_42: junk 		   "
class WolfStatic42 : Actor
{
    Default
    {
        +NOBLOCKMAP
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S042 A -1;
        Stop;
    }
}

// statinfo[43] sprite SPR_STAT_43: junk            "
class WolfStatic43 : Actor
{
    Default
    {
        +NOBLOCKMAP
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S043 A -1;
        Stop;
    }
}

// statinfo[44] sprite SPR_STAT_44: pots            "
class WolfStatic44 : Actor
{
    Default
    {
        +NOBLOCKMAP
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S044 A -1;
        Stop;
    }
}

// statinfo[45] sprite SPR_STAT_45: stove           " (SOD:gibs)
class WolfStatic45 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S045 A -1;
        Stop;
    }
}

// statinfo[46] sprite SPR_STAT_46: spears          " (SOD:gibs)
class WolfStatic46 : Actor
{
    Default
    {
        +SOLID
        Radius 32;
        Height 64;
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S046 A -1;
        Stop;
    }
}

// statinfo[47] sprite SPR_STAT_47: vines			"
class WolfStatic47 : Actor
{
    Default
    {
        +NOBLOCKMAP
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S047 A -1;
        Stop;
    }
}

// statinfo[48] sprite SPR_STAT_26: Clip            "  // TODO Phase 2 pickup: bo_clip2
class WolfStatic48 : Actor
{
    Default
    {
        +NOBLOCKMAP
        +NOGRAVITY
    }
    States
    {
    Spawn:
        S048 A -1;
        Stop;
    }
}

// dead guard (map code 124, MAP-004): SPR_GRD_DEAD, inert
class WolfDeadGuard : Actor
{
    Default
    {
        +NOBLOCKMAP
        +NOGRAVITY
    }
    States
    {
    Spawn:
        SDED A -1;
        Stop;
    }
}

